files:
  include: 'src/sass/**/*.s+(a|c)ss'
rules:
  no-transition-all: 0
  no-important: 0
  no-vendor-prefixes: 0
  class-name-format: 
    - 1
    - 
      convention: hyphenatedbem
  no-duplicate-properties:
    - 1
    -
      exclude:
        - background