version: 2

jobs:
  build:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/personal-portfolio

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: Install npm packages
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
        
      - run:
          name: Run lint
          command: npm run lint

      - run:
          name: Run Build
          command: npm run lint
          filters:
            branches:
              only: master


